/**
 * Phase 44 §1 — generate docs/ingestion-map.md.
 *
 * The host inventory and the contract-coverage count are DERIVED from the tree,
 * not typed. A hand-maintained inventory of ingestion paths is a second
 * definition of what we ingest, and the A7 rule exists because "the N sources"
 * is exactly the claim that turns out to be N+1.
 *
 *   node scripts/gates/ingestion-map.mjs           write the map
 *   node scripts/gates/ingestion-map.mjs --check   exit 1 if it is out of date
 */
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CONTRACTS } from '../../workers/lib/sourceContracts.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const MAP_PATH = join(ROOT, 'docs/ingestion-map.md');

/** Every outbound host the worker names, with how many times. */
function workerHosts() {
  const src = readFileSync(join(ROOT, 'workers/fetch-s1.js'), 'utf8');
  const counts = new Map();
  for (const m of src.matchAll(/https?:\/\/([a-zA-Z0-9.-]+)/g)) {
    const h = m[1];
    if (h.includes('kkme')) continue;            // our own surfaces, not ingestion
    counts.set(h, (counts.get(h) ?? 0) + 1);
  }
  return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
}

function listDir(rel, filter) {
  const p = join(ROOT, rel);
  return existsSync(p) ? readdirSync(p).filter(filter).sort() : [];
}

function render() {
  const hosts = workerHosts();
  const contracted = new Set(Object.values(CONTRACTS).map((c) => c.host));
  const vps = listDir('scripts/vps', (f) => f.endsWith('.py') || f.endsWith('.sh'));
  const mm = listDir('tools/consultancy/mature-markets', (f) => f.startsWith('fetch-'));
  const wf = listDir('.github/workflows', (f) => f.endsWith('.yml'));

  const hostRows = hosts.map(([h, n]) => {
    const c = Object.values(CONTRACTS).find((x) => x.host === h);
    return `| \`${h}\` | ${n} | ${c ? `✅ \`${c.id}\`` : '—'} | ${c ? `${c.freshness_hours} h` : '—'} | ${c ? `${c.volume[0]}–${c.volume[1]}` : '—'} |`;
  });

  return `# Ingestion map

**Generated by \`scripts/gates/ingestion-map.mjs\` — do not hand-edit.**
\`--check\` is asserted by the suite, so a new ingestion path added without regenerating
this file is a red test rather than a stale document.

## Why this exists

Every data path here has failed at least once, and every time the failure was invisible
for days: BTD's cert chain (12 days), the S1 branch timeout (9 ticks, a week), NordPool
serving HTML where JSON was expected, the LV register writing \`closed\` as a single space,
cp1257 mojibake reaching the intel feed, a manifest refresh destroying 131,472 rows with
every checksum passing. That is not bad luck. It is that ingestion had no contract: a
fetcher asked for bytes, got bytes, and whatever those bytes were became the truth.

## Coverage

| | count |
|---|---|
| distinct external hosts named in the worker | **${hosts.length}** |
| of those, carrying a declared contract | **${hosts.filter(([h]) => contracted.has(h)).length}** |
| declared contracts in total (incl. one not yet ingested) | **${Object.keys(CONTRACTS).length}** |
| VPS scripts | ${vps.length} |
| mature-market fetchers | ${mm.length} |
| GitHub Actions workflows | ${wf.length} |

Contract coverage is **${hosts.filter(([h]) => contracted.has(h)).length}/${hosts.length}** of worker hosts. That is the honest number and it is low:
this phase built the mechanism and declared contracts for the sources whose failures are
on record. The remainder are listed below with no contract, which is the point — an
undeclared source is visibly undeclared rather than invisibly unchecked.

## Worker hosts

\`${'`'}Refs\`${'`'} counts textual occurrences in \`workers/fetch-s1.js\`, not requests per run.

| host | refs | contract | freshness | volume envelope |
|---|---|---|---|---|
${hostRows.join('\n')}

## Declared contracts

${Object.values(CONTRACTS).map((c) => `### \`${c.id}\`

- **host** \`${c.host}\` · **transport** ${c.transport} · **units** ${c.units}
- **cadence** ${c.cadence}
- **freshness** ${c.freshness_hours} h — derived from the source's own cadence, not a global constant
- **volume envelope** ${c.volume[0]}–${c.volume[1]} (outside this band a run is an anomaly, not a result)
- **timezone** ${c.timezone}
- **required** ${c.required.map((r) => `\`${r}\``).join(', ')}
- ${c.notes}`).join('\n\n')}

## Other ingestion paths

**VPS** (\`scripts/vps/\`): ${vps.map((f) => `\`${f}\``).join(' · ')}

**Mature markets** (\`tools/consultancy/mature-markets/\`): ${mm.map((f) => `\`${f}\``).join(' · ')}

**Workflows** (\`.github/workflows/\`): ${wf.map((f) => `\`${f}\``).join(' · ')}

## Fixture discipline (B-043)

All ${mm.length} mature-market fetchers used to overwrite their own recorded sample on every
run. A fixture exists to be a photograph of the source **as of when the parser was
written**, so that a contract test fails when the source changes shape. A fetcher that
re-photographs the source on every run keeps fixture and source in permanent agreement —
the test then passes forever, including on the run where the source changed and the parser
started producing empty output. Not merely useless at that point: actively reassuring.

Fixture writes now route through \`fixture-guard.mjs\` and no-op unless \`--record-fixture\`
is passed. Enforced by \`scripts/gates/no-fetcher-writes-fixtures.sh\`.
`;
}

const out = render();
if (process.argv.includes('--check')) {
  if (!existsSync(MAP_PATH) || readFileSync(MAP_PATH, 'utf8') !== out) {
    console.error('docs/ingestion-map.md is out of date — run `node scripts/gates/ingestion-map.mjs`');
    process.exit(1);
  }
  console.log('docs/ingestion-map.md matches the tree');
  process.exit(0);
}
writeFileSync(MAP_PATH, out);
console.log(`wrote ${MAP_PATH}`);
